name: rehab_games
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0

environment:
  sdk: ^3.7.2

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.32.0
  provider: ^6.1.5
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  english_words: ^4.0.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4 
  google_sign_in: ^6.2.2
  fl_chart: ^1.0.0
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  intl: ^0.20.2
  flutter_launcher_icons: ^0.14.3
  image_picker: ^1.0.7
  uuid: ^4.0.0
  firebase_storage: ^11.6.4
  firebase_messaging: ^14.9.4
  firebase_analytics: ^10.8.0
  badges: ^3.1.2
  rxdart: ^0.28.0


dev_dependencies:
  flutter_test:
    sdk: flutter


  
  

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/avatars/avatar_bisan.png
    - assets/avatars/cat.png
    - assets/avatars/girl.png
    - assets/avatars/user.png
    - assets/avatars/id-card.png
    - assets/icons/code.png
    - assets/icons/led.png
    - assets/icons/audio.png
    - assets/icons/brain.png
    - assets/icons/sound.png
    - assets/icons/chat.png
    - assets/icons/colorword.png
    - assets/icons/coin.png
    - assets/icons/store.png
    - assets/icons/lock.png
    - assets/icons/unlocked.png
    - assets/background/background.png
    - assets/background/shop.png
    - assets/background/net.png
    - assets/background/innershop.png
    - assets/background/chat.png
    - assets/avatars/classic/nerdy-nerd.png
    - assets/avatars/classic/blond-buddy.png
    - assets/avatars/classic/happy-heart.png
    - assets/avatars/classic/sharp-eyes.png
    - assets/avatars/classic/hoodie-girl.png
    - assets/avatars/classic/fresh-face.png
    - assets/avatars/classic/night-spark.png
    - assets/avatars/classic/crazy-cool.png
    - assets/avatars/classic/bold-aura.png
    - assets/avatars/classic/cool-button.png
    - assets/avatars/classic/bubble-pink.png
    - assets/avatars/classic/gentle-guy.png
    - assets/avatars/classic/active-snap.png
    - assets/avatars/classic/slow-beat.png
    - assets/avatars/classic/happy-gold.png
    - assets/avatars/classic/wise-dad.png
    - assets/avatars/classic/flower-scout.png
    - assets/avatars/classic/cheer-bro.png
    - assets/avatars/classic/twist-vibe.png
    - assets/avatars/classic/green-pulse.png
    - assets/avatars/classic/hat-kid.png
    - assets/avatars/classic/beach-bloom.png
    - assets/avatars/classic/calm-suit.png
    - assets/avatars/classic/soft-breeze.png
    - assets/avatars/classic/candy-puff.png
    - assets/avatars/classic/tiny-shine.png
    - assets/avatars/classic/hype-loop.png
    - assets/avatars/classic/sky-boy.png
    - assets/avatars/boutique/midnight-ghost.png
    - assets/avatars/boutique/turbo-ninja.png
    - assets/avatars/boutique/loot-pirate.png
    - assets/avatars/boutique/halloween-pumpkin.png
    - assets/avatars/boutique/lunar-angel.png
    - assets/avatars/boutique/gear-racer.png
    - assets/avatars/boutique/Eclipse-astronaut.png
    - assets/avatars/boutique/masked-superhero.png
    - assets/avatars/boutique/pixal-robot.png
    - assets/avatars/boutique/Quantum-professor.png
    - assets/avatars/boutique/soft-farmer.png
    - assets/avatars/boutique/rich-ceo.png
    - assets/avatars/boutique/wall-goalkeeper.png
    - assets/avatars/boutique/neon-alien.png
    - assets/avatars/boutique/stone-caveman.png
    - assets/avatars/boutique/galaxy-robot.png
    - assets/avatars/boutique/happy-african-woman.png
    - assets/avatars/boutique/bold-basketball-player.png
    - assets/avatars/boutique/metro-police.png
    - assets/avatars/boutique/one eye-monster.png
    - assets/avatars/boutique/blue skin-revived.png
    - assets/avatars/boutique/phantom-spyware.png
    - assets/avatars/boutique/dark-villain.png
    - assets/avatars/boutique/toxic-cyborg.png
    - assets/avatars/boutique/wicked-wizard.png
    - assets/avatars/boutique/blitz-frankenstein.png
    - assets/avatars/boutique/jet-pilot.png
    - assets/avatars/boutique/party-dj.png
    - assets/avatars/animals/wild-gorilla.png
    - assets/avatars/animals/bouncy-meerkat.png
    - assets/avatars/animals/silly-chicken.png
    - assets/avatars/animals/magic-rabbit.png
    - assets/avatars/animals/sleepy-bear.png
    - assets/avatars/animals/cookie-panda.png
    - assets/avatars/animals/snuggle-cat.png
    - assets/avatars/animals/brave-dog.png
    - assets/avatars/animals/lazy-duck.png
    - assets/avatars/animals/fluffy-owl.png
    - assets/avatars/animals/berry-sea-lion.png
    - assets/avatars/animals/flip-lion.png
    - assets/avatars/animals/skate-penguin.png
    - assets/avatars/animals/swirl-hen.png
    - assets/avatars/animals/sky-giraffe.png
    - assets/avatars/animals/chill-hippo.png
    - assets/avatars/animals/bold-tiger.png
    - assets/avatars/animals/splash-shark.png
    - assets/avatars/animals/gold-pufferfish.png
    - assets/avatars/animals/marble-eagle.png
    - assets/avatars/animals/toddy-frog.png
    - assets/avatars/animals/sand-camel.png
    - assets/avatars/animals/slow-sloth.png
    - assets/avatars/animals/wiggle-cow.png
    - assets/avatars/animals/random-deer.png
    - assets/avatars/animals/tusk-walrus.png
    - assets/avatars/animals/fuzzy-ostrich.png
    - assets/avatars/animals/wise-elephant.png
    - assets/nav/home.png
    - assets/nav/network.png
    - assets/nav/cart.png
  fonts:
    - family: LuckiestGuy
      fonts:
        - asset: assets/fonts/LuckiestGuy-Regular.ttf
    - family: Bangers
      fonts:
        - asset: assets/fonts/Bangers-Regular.ttf



  
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
